"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Alumno_1 = require("./Alumno");
const Documento_1 = require("./Documento");
const GestorLegajos_1 = require("./GestorLegajos");
const Materia_1 = require("./Materia");
let a1 = new Alumno_1.Alumno("Ezequiel", "Gonzalez", new Documento_1.Documento("DNI", "40912321"), "Alem 123", [new Materia_1.Materia("Matemática", 6.6, 7, 8), new Materia_1.Materia("Historia", 3, 9, 7), new Materia_1.Materia("Física", 3, 2, 5)]);
let a2 = new Alumno_1.Alumno("Agustin", "Paredes", new Documento_1.Documento("DNI", "42123001"), "Magallanes 222", [new Materia_1.Materia("Matemática", 4, 6.5, 8), new Materia_1.Materia("Historia", 6, 5, 7), new Materia_1.Materia("Física", 4, 7, 8)]);
let a3 = new Alumno_1.Alumno("Camila", "Uribe", new Documento_1.Documento("DNI", "41422524"), "Rosas 223", [new Materia_1.Materia("Matemática", 9, 8, 8), new Materia_1.Materia("Historia", 10, 9, 7), new Materia_1.Materia("Física", 9, 8, 9)]);
let a4 = new Alumno_1.Alumno("Paola", "Echenique", new Documento_1.Documento("DNI", "42111912"), "20 Junio 111", [new Materia_1.Materia("Matemática", 3, 5, 8), new Materia_1.Materia("Historia", 7, 4, 8), new Materia_1.Materia("Física", 4, 7, 8)]);
let a5 = new Alumno_1.Alumno("Vanesa", "Martinez", new Documento_1.Documento("DNI", "44012200"), "Bahia Blanca 321", [new Materia_1.Materia("Matemática", 6.6, 7.5, 6), new Materia_1.Materia("Historia", 9, 6, 8), new Materia_1.Materia("Física", 7.7, 8, 6)]);
let a6 = new Alumno_1.Alumno("Maximiliano", "Perez", new Documento_1.Documento("DNI", "41000120"), "Belgrano 101", [new Materia_1.Materia("Matemática", 7.5, 8, 4), new Materia_1.Materia("Historia", 6, 5, 6), new Materia_1.Materia("Física", 5, 5, 7)]);
let a7 = new Alumno_1.Alumno("Lucas", "Lopez", new Documento_1.Documento("DNI", "44234092"), "Los Andes 912", [new Materia_1.Materia("Matemática", 3, 5, 4), new Materia_1.Materia("Historia", 5, 6, 6), new Materia_1.Materia("Física", 6, 5, 5)]);
let a8 = new Alumno_1.Alumno("Esteban", "Garay", new Documento_1.Documento("DNI", "39412911"), "Alem 478", [new Materia_1.Materia("Matemática", 9, 10, 9), new Materia_1.Materia("Historia", 10, 7, 8), new Materia_1.Materia("Física", 8, 10, 8)]);
let a9 = new Alumno_1.Alumno("Ariel", "Fernandez", new Documento_1.Documento("DNI", "39222501"), "Urquiza 432", [new Materia_1.Materia("Matemática", 7, 7, 8), new Materia_1.Materia("Historia", 9, 8, 7), new Materia_1.Materia("Física", 8, 9, 7)]);
let a10 = new Alumno_1.Alumno("Esteban", "Garay", new Documento_1.Documento("DNI", "39412911"), "Alem 478", [new Materia_1.Materia("Matemática", 6, 7, 8), new Materia_1.Materia("Historia", 6.6, 7.6, 5), new Materia_1.Materia("Física", 8.5, 6, 7)]);
let a11 = new Alumno_1.Alumno("Esteban", "Garay", new Documento_1.Documento("DNI", "39412911"), "Alem 478", [new Materia_1.Materia("Matemática", 5, 4, 6), new Materia_1.Materia("Historia", 5, 5, 8), new Materia_1.Materia("Física", 6, 6, 7)]);
let alumnos = [a1, a2, a3, a4];
let alumnos2 = [a5, a6, a7, a8, a9, a10, a11];
let gestor = new GestorLegajos_1.GestorLegajos(alumnos);
console.table(gestor);
alumnos2.forEach(alumno => {
    gestor.inscribir(alumno);
});
console.table(gestor);
console.log("Nota promedio alumno 1");
console.log(gestor.getNotaPromedioDeUnAlumno(a1));
console.log("promedio de todos los inscriptos");
console.log(gestor.getNotaPromedioDeLosAlumnos());
